//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SebProject.InterestRateService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceModels.CustomerDetailsModel", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceModelsCustomerDetailsModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SebProject.InterestRateService.ServiceModelsAgreementDTO[] AgreementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SebProject.InterestRateService.ServiceModelsAgreementDTO[] Agreements {
            get {
                return this.AgreementsField;
            }
            set {
                if ((object.ReferenceEquals(this.AgreementsField, value) != true)) {
                    this.AgreementsField = value;
                    this.RaisePropertyChanged("Agreements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceModels.AgreementDTO", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceModelsAgreementDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MarginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonaIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Margin {
            get {
                return this.MarginField;
            }
            set {
                if ((this.MarginField.Equals(value) != true)) {
                    this.MarginField = value;
                    this.RaisePropertyChanged("Margin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonaId {
            get {
                return this.PersonaIdField;
            }
            set {
                if ((this.PersonaIdField.Equals(value) != true)) {
                    this.PersonaIdField = value;
                    this.RaisePropertyChanged("PersonaId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceModels.AgreementForRate", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceModelsAgreementForRate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgreementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgreementId {
            get {
                return this.AgreementIdField;
            }
            set {
                if ((this.AgreementIdField.Equals(value) != true)) {
                    this.AgreementIdField = value;
                    this.RaisePropertyChanged("AgreementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceModels.InterestRates", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceModelsInterestRates : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FirstRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SecondRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FirstRate {
            get {
                return this.FirstRateField;
            }
            set {
                if ((this.FirstRateField.Equals(value) != true)) {
                    this.FirstRateField = value;
                    this.RaisePropertyChanged("FirstRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SecondRate {
            get {
                return this.SecondRateField;
            }
            set {
                if ((this.SecondRateField.Equals(value) != true)) {
                    this.SecondRateField = value;
                    this.RaisePropertyChanged("SecondRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceModels.CustomerDTO", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceModelsCustomerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PersonalIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonalId {
            get {
                return this.PersonalIdField;
            }
            set {
                if ((this.PersonalIdField.Equals(value) != true)) {
                    this.PersonalIdField = value;
                    this.RaisePropertyChanged("PersonalId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InterestRateService.IInterestRateService")]
    public interface IInterestRateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/GetAgreements", ReplyAction="http://tempuri.org/IInterestRateService/GetAgreementsResponse")]
        SebProject.InterestRateService.ServiceModelsCustomerDetailsModel GetAgreements(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/GetAgreements", ReplyAction="http://tempuri.org/IInterestRateService/GetAgreementsResponse")]
        System.Threading.Tasks.Task<SebProject.InterestRateService.ServiceModelsCustomerDetailsModel> GetAgreementsAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/GetCalculatedInterestRates", ReplyAction="http://tempuri.org/IInterestRateService/GetCalculatedInterestRatesResponse")]
        SebProject.InterestRateService.ServiceModelsInterestRates GetCalculatedInterestRates(SebProject.InterestRateService.ServiceModelsAgreementForRate agreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/GetCalculatedInterestRates", ReplyAction="http://tempuri.org/IInterestRateService/GetCalculatedInterestRatesResponse")]
        System.Threading.Tasks.Task<SebProject.InterestRateService.ServiceModelsInterestRates> GetCalculatedInterestRatesAsync(SebProject.InterestRateService.ServiceModelsAgreementForRate agreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/CreateCustomer", ReplyAction="http://tempuri.org/IInterestRateService/CreateCustomerResponse")]
        int CreateCustomer(SebProject.InterestRateService.ServiceModelsCustomerDTO customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/CreateCustomer", ReplyAction="http://tempuri.org/IInterestRateService/CreateCustomerResponse")]
        System.Threading.Tasks.Task<int> CreateCustomerAsync(SebProject.InterestRateService.ServiceModelsCustomerDTO customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/CreateAgreement", ReplyAction="http://tempuri.org/IInterestRateService/CreateAgreementResponse")]
        int CreateAgreement(SebProject.InterestRateService.ServiceModelsAgreementDTO agreement);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInterestRateService/CreateAgreement", ReplyAction="http://tempuri.org/IInterestRateService/CreateAgreementResponse")]
        System.Threading.Tasks.Task<int> CreateAgreementAsync(SebProject.InterestRateService.ServiceModelsAgreementDTO agreement);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInterestRateServiceChannel : SebProject.InterestRateService.IInterestRateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InterestRateServiceClient : System.ServiceModel.ClientBase<SebProject.InterestRateService.IInterestRateService>, SebProject.InterestRateService.IInterestRateService {
        
        public InterestRateServiceClient() {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InterestRateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SebProject.InterestRateService.ServiceModelsCustomerDetailsModel GetAgreements(int customerId) {
            return base.Channel.GetAgreements(customerId);
        }
        
        public System.Threading.Tasks.Task<SebProject.InterestRateService.ServiceModelsCustomerDetailsModel> GetAgreementsAsync(int customerId) {
            return base.Channel.GetAgreementsAsync(customerId);
        }
        
        public SebProject.InterestRateService.ServiceModelsInterestRates GetCalculatedInterestRates(SebProject.InterestRateService.ServiceModelsAgreementForRate agreement) {
            return base.Channel.GetCalculatedInterestRates(agreement);
        }
        
        public System.Threading.Tasks.Task<SebProject.InterestRateService.ServiceModelsInterestRates> GetCalculatedInterestRatesAsync(SebProject.InterestRateService.ServiceModelsAgreementForRate agreement) {
            return base.Channel.GetCalculatedInterestRatesAsync(agreement);
        }
        
        public int CreateCustomer(SebProject.InterestRateService.ServiceModelsCustomerDTO customer) {
            return base.Channel.CreateCustomer(customer);
        }
        
        public System.Threading.Tasks.Task<int> CreateCustomerAsync(SebProject.InterestRateService.ServiceModelsCustomerDTO customer) {
            return base.Channel.CreateCustomerAsync(customer);
        }
        
        public int CreateAgreement(SebProject.InterestRateService.ServiceModelsAgreementDTO agreement) {
            return base.Channel.CreateAgreement(agreement);
        }
        
        public System.Threading.Tasks.Task<int> CreateAgreementAsync(SebProject.InterestRateService.ServiceModelsAgreementDTO agreement) {
            return base.Channel.CreateAgreementAsync(agreement);
        }
    }
}
